apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    value: pubcode
  - name: DATABASE
    description: Postgres database name
    value: database
  - name: API
    description: API name
    value: api
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: PROMOTE
    description: Dummy param, for convenience in deployments
    generate: expression
  - name: GENERATED_ADMIN_PASSWORD
    description: Password for the mongodb connection admin user.
    from: "[a-zA-Z0-9]{32}"
    generate: expression
  - name: API_KEY
    description: KEY for the API
    from: "[a-zA-Z0-9]{32}"
    generate: expression
  - name: EMAIL_RECIPIENTS
    description: Email Recipients
    required: true
  - name: CHES_TOKEN_URL
    description: Token URL for CHES
    required: true
  - name: CHES_CLIENT_ID
    description: Client ID for CHES
    required: true
  - name: CHES_CLIENT_SECRET
    description: Client Secret for CHES
    required: true
  - name: CHES_API_URL
    description: URL for CHES API
    required: true

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-${DATABASE}
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      database-admin-password: ${GENERATED_ADMIN_PASSWORD}
      database-admin-user: admin
      database-name: ${NAME}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-${API}
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      api_key: ${API_KEY}
      email_recipients: ${EMAIL_RECIPIENTS}
      ches_token_url: ${CHES_TOKEN_URL}
      ches_client_id: ${CHES_CLIENT_ID}
      ches_client_secret: ${CHES_CLIENT_SECRET}
      ches_api_url: ${CHES_API_URL}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      podSelector: {}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: quickstart-network-security-policy
    spec:
      podSelector: {}
      ingress:
        - from:
            - podSelector: {}
      policyTypes:
        - Ingress
