apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    value: public-code
  - name: DATABASE
    description: Postgres database name
    value: database
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: PROMOTE
    description: Dummy param, for convenience in deployments
    generate: expression
  - name: GENERATED_ADMIN_PASSWORD
    description: Password for the mongodb connection user.
    from: "[a-z]{32}"
    generate: expression
  - name: API_KEY
    description: KEY for the API
    from: "[a-zA-Z0-9]{32}"
    generate: expression
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-${DATABASE}
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      database-admin-password: ${GENERATED_ADMIN_PASSWORD}
      database-admin-user: default
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-backend
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      api_key: ${API_KEY}

  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      podSelector: {}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: quickstart-network-security-policy
    spec:
      podSelector: {}
      ingress:
        - from:
            - podSelector: {}
      policyTypes:
        - Ingress
