name: Pull Request Closed

on:
  pull_request:
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  cleanup:
    name: Cleanup and Image Promotion
    uses: bcgov/actions-openshift/.github/workflows/.pr-close.yml@50414269295ed040baf0d05cb4c7f4d76c7bcd8c # v0.2.0
    permissions:
      packages: write
    secrets:
      oc_namespace: ${{ vars.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      cleanup: helm
      packages: api frontend database
