name: Pull Request Closed

on:
  pull_request:
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  cleanup:
    name: Cleanup and Image Promotion
    uses: bcgov/actions-openshift/.github/workflows/.pr-close.yml@97cb3f8a5a6d134594c85224d3f593e3c0e90647 # v0.4.0
    permissions:
      packages: write
    secrets:
      oc_namespace: ${{ vars.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      cleanup: helm
      packages: api frontend database
