name: Pull Request

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  builds:
    name: Builds
    runs-on: ubuntu-26.04
    permissions:
      contents: read
      attestations: write
      id-token: write
      packages: write
    strategy:
      matrix:
        package: [api, database, frontend]
    steps:
      - uses: actions/checkout@v7
      - uses: bcgov/actions/builder@4026bfd276b8a5839029106099b13edfb594b2c3 # v0.8.0
        with:
          package: ${{ matrix.package }}
          tags: ${{ github.event.number || github.sha }}
          tag_fallback: latest
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: shrink/actions-docker-registry-tag@e6aaef25c595b6e0edd18bf4c7dbfea3abd43299 # v5
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ github.event.number || github.sha }}
          tags: ${{ github.sha }}

  deploys:
    name: Deploys
    needs: [builds]
    permissions:
      contents: read
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      autoscaling: false
      tag: ${{ github.event.number }}
      release_name: pubcode-${{ github.event.number }}
      params: |
        --set-string global.repository=${{ github.repository }}  \
        --set-string database.containers[0].tag="${{ github.sha }}" \
        --set-string database.initContainers[0].tag="${{ github.sha }}" \
        --set-string api.containers[0].tag="${{ github.sha }}" \
        --set-string api.containers[0].resources.requests.cpu="30m" \
        --set-string api.containers[0].resources.requests.memory="50Mi" \
        --set-string frontend.containers[0].tag="${{ github.sha }}" \
        --set-string frontend.containers[0].resources.requests.cpu="30m" \
        --set-string frontend.containers[0].resources.requests.memory="50Mi" \
        --set-string database.containers[0].resources.requests.cpu="30m" \
        --set-string database.containers[0].resources.requests.memory="50Mi" \
        --set-string database.initContainers[0].resources.requests.cpu="30m" \
        --set-string database.initContainers[0].resources.requests.memory="50Mi" \
        --set-string database.pvc.size="350Mi" \
        --set-string global.env.VITE_SCHEMA_BRANCH=${{ github.event.pull_request.head.ref }} \

  tests:
    name: Tests
    needs: [deploys]
    permissions:
      contents: read
    uses: ./.github/workflows/.tests.yml
    with:
      target: ${{ github.event.number }}

  results:
    name: Results
    if: always()
    needs: [builds, deploys, tests]
    runs-on: ubuntu-26.04
    timeout-minutes: 1
    steps:
      - name: Fail if any dependent job failed or was cancelled
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
