name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: bcgov/actions/pr-validate@ac9d89eede94f5f58d3446784c94cff634d98eac # v0.6.0
        with:
          add_markdown: |
            ---
            Thanks for the PR!

            Any successful deployments (not always required) will be available below.
            [API](https://${{ github.event.repository.name }}-${{ github.event.number }}-api.apps.silver.devops.gov.bc.ca/) available
            [Frontend](https://${{ github.event.repository.name }}-${{ github.event.number }}.apps.silver.devops.gov.bc.ca/) available

            Once merged, code will be promoted and handed off to following workflow run.
            [Main Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge.yml)
